name: Build and distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-android@v1
        with:
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
          # optionals
          build-cmd: flutter build apk --release
          working-directory: ./launcher/

      - name: ReleaseMe - GitHub Release Management
        uses: dev-build-deploy/release-me@v0.18.2
        with:
          files: ./launcer/build/app/outputs/flutter-apk/app-release.apk
          token: ${{ github.token }}
